= Creating Roles for Multi RHEL Compute Nodes (Continued)

Continue further with the below mentioned steps:

. Move the RHEL 9.2 Compute nodes from the source role to the new role:
+
----
python3 /usr/share/openstack-tripleo-heat-templates/tools/baremetal_transition.py  --baremetal-deployment /home/stack/tripleo-overcloud-baremetal-deployment.yaml  --src-role Compute  --dst-role ComputeRHEL-9.2 overcloud-novacompute-0
----
+
This script includes the baremetal-deployment.yaml file that you used to provision your nodes during overcloud adoption.
+
- Compute_source_role was replaced with the name of the source Compute role that contains the nodes that you are moving to your new role: Compute
- Compute_destination_role was replaced with the name of your new role: ComputeRHEL-9.2
- Compute-0 Compute-1 Compute-2 was replaced with the names of the nodes that you are moving to your new role: overcloud-novacompute-0

. Reprovision the node overcloud-novacompute-0 to update the environment files in the stack with the new role location:
+
----
openstack overcloud node provision --stack overcloud --output /home/stack/overcloud_adopt/baremetal-deployment.yaml /home/stack/tripleo-overcloud-baremetal-deployment.yaml
----

. Use the following variables that we used in the overcloud adoption section:
+
----
export NAMESPACE='"namespace":"registry.redhat.io/rhosp-rhel9",'
export EL8_NAMESPACE='"namespace":"registry.redhat.io/rhosp-rhel8",'
export EL9_TAGS='"tag":"17.1",'
export EL8_TAGS='"tag":"17.1",'
export CEPH_TAGS='"ceph_tag":"latest",'
export NEUTRON_DRIVER='"neutron_driver":"ovn",'
----

. Include any Compute roles that are remaining on RHEL 8.4 in the COMPUTE_ROLES parameter, and run the following script. For example, if you have a role called ComputeRHEL8 role that contains the nodes that are remaining on RHEL 8.4, include this role in the COMPUTE_ROLES parameter as --role ComputeRHEL-8.4.
+
----
python3 /usr/share/openstack-tripleo-heat-templates/tools/multi-rhel-container-image-prepare.py \
--local-push-destination \
    --role ComputeRHEL-8.4  \
    --enable-multi-rhel \
    --excludes collectd --excludes nova-libvirt \
    --minor-override "{${EL8_TAGS}${EL8_NAMESPACE}${CEPH_TAGS}${NEUTRON_DRIVER}\"no_tag\":\"not_used\"}" --major-override "{${EL9_TAGS}${NAMESPACE}${CEPH_TAGS}${NEUTRON_DRIVER}\"no_tag\":\"not_used\"}"  \
    --output-env-file /home/stack/containers-prepare-parameter.yaml
----

. Add credentials to our generated containers-prepare-parameter.yaml with the following command:
+
----
cat >> /home/stack/containers-prepare-parameter.yaml <<EOF           
  ContainerImageRegistryLogin: true
  ContainerImageRegistryCredentials:
    registry.redhat.io:
      1979710|test-rhosp16.1: eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJhODU0YTEzMTI5NzA0MmY0YmVmYjBlMTM1OWI2OTZiYSJ9.mYlBdmv2vssWv5uQ5kI9__qZLmYn48AG_DghKtzjmTx5n3O1l-MU1sUMGCSJaekGP6m6OSWLfz5Rl82Px4BHZ7SDnSRtd8SNvsHmRkS85_djRwi5gW4V3TXjXhzV_e0rw-q8SmnMpe7uZklRKfJCsziPfrOziAnSLAqQAkcPujwXSpg2dzKtZjWjgfjldGEraIj3FBdY9ISs7ZilE4HdRHEvMseHtZzFu93Td7iOcsAHRkK78evoDntrXmoVjAueDc_kU_nCJ8l1-vuw3W0TJ8_5HZ0gqQur1G_NORq7qIh3Ffq0x7mLTNYpKcVf4Sg-T6wwWDxL2U3oBX6r9HKm8ZvasPB-D0mV_zd6we1EF4CPcXUBSzat1tPzJTISTp8QIOj8dnJ2vyQjwBC9A4VTlwQFr95Z4m3sGhjwqeTi-iBTTWGzlXettTsQfkpxK34qd6G5bGKIwRQsZ27JkPxhGRmEqP7H2d-Ann08NzKqOXYnYBeNUybOxGlvutRtiH0CnsY_NJVqZ3sTIoZHTTbUPdSKtiYW2XNwXbQ_L8jKaXtOAN1tPi-R-thx-9XFLwVJh9uXe9mZ1uH0mh8-oMXV5iDCVXmhmR58BUcWqb3EbLD9AKO2iwLZTFbsa-NRjEF3UgZgqaGx1IDbe7EQlgiqeXmZUfrpdO9YIjks3RGxp70
EOF
----

. Move the RHEL 8.4 Compute nodes from the source role to the new role:
+
----
python3 /usr/share/openstack-tripleo-heat-templates/tools/baremetal_transition.py  --baremetal-deployment /home/stack/tripleo-overcloud-baremetal-deployment.yaml  --src-role Compute  --dst-role ComputeRHEL-8.4 overcloud-novacompute-1
----
+
This script includes the baremetal-deployment.yaml file that you used to provision your nodes during overcloud adoption.
+
- Compute_source_role was replaced with the name of the source Compute role that contains the nodes that you are moving to your new role: Compute
- Compute_destination_role was replaced with the name of your new role: ComputeRHEL-8.4
- Compute-0 Compute-1 Compute-2 was replaced with the names of the nodes that you are moving to your new role: overcloud-novacompute-1

. Reprovision the node overcloud-novacompute-1 to update the environment files in the stack with the new role location:
+
----
openstack overcloud node provision --stack overcloud --output /home/stack/overcloud_adopt/baremetal-deployment.yaml /home/stack/tripleo-overcloud-baremetal-deployment.yaml
----
